name: Generate Snake Animation

on:
  schedule:
    - cron: "0 12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: alencarrgabriel
          svg_out_path: dist/github-snake.svg

      - name: Push snake animation to the repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
